sudo: false
language: php
os:
  - linux
php:
  - 8.0
  - nightly
jobs:
  allow_failures:
  - php: nightly
before_script:
  - composer self-update --2
  - COMPOSER_MEMORY_LIMIT=5G composer install --prefer-dist
script: composer run-script test
notifications:
  email: false
branches:
  only:
  - main