sudo: false
language: php
os:
  - linux
php:
  - 7.4
before_script:
  - composer self-update
  - composer install --no-dev --prefer-dist
script: vendor/bin/phpunit
notifications:
  email: false
branches:
  only:
  - master
